inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rspec

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
    Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
